AztuLibSystem/AztuLibSystem/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AztuLibSystem.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }
        public decimal Price  { get; set; }

        public int CategoryId { get; set; }
        public Category Category { get; set; }
    }
}

AztuLibSystem/AztuLibSystem/Areas/AdminF/Controllers/SliderController.cs
using AztuLibSystem.DAL;
using AztuLibSystem.Extentions;
using AztuLibSystem.Helpers;
using AztuLibSystem.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace AztuLibSystem.Areas.AdminF.Controllers
{
    [Area("AdminF")]
    public class SliderController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;
        public SliderController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Slider> sliders = _context.Sliders.ToList();
            return View(sliders);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Create(Slider slider)
        {
            if(ModelState["Photo"].ValidationState==Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
            {
                
                return View();
            }
            if (!slider.Photo.IsImage())
            {
                ModelState.AddModelError("Photo", "accept only image");
                return View();
            }
            if (slider.Photo.ImageSize(10000))
            {
                ModelState.AddModelError("Photo", "1Mb Yuxari ola bilmez");
                return View();
            }
            //string path = @"C:\Users\aslan\Desktop\Final Main\AztuLibSystem\AztuLibSystem\wwwroot\img\slider\";
            string fileName = await slider.Photo.SaveImage(_env, "img");
            Slider newSlier = new Slider();
            newSlier.ImageUrl = await slider.Photo.SaveImage(_env, "img");      
            await _context.Sliders.AddAsync(newSlier);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Slider dbSlider = await _context.Sliders.FindAsync(id);
            if (dbSlider == null) return NotFound();

            Helper.DeleteFile(_env, "img", dbSlider.ImageUrl);

            _context.Sliders.Remove(dbSlider);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index"); 
        }
        
    }
}

AztuLibSystem/AztuLibSystem/Controllers/ProductController.cs
using AztuLibSystem.DAL;
using AztuLibSystem.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AztuLibSystem.Controllers
{
    public class ProductController : Controller
    {
        private AppDbContext _context;
        public ProductController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            ViewBag.ProductCount = _context.Products.Count();
            List<Product> products = _context.Products.Include(p => p.Category).Take(2).ToList();
            return View(products);
        }
        public IActionResult LoadMore(int skip)
        {
            List<Product> products = _context.Products.Include(p => p.Category).Skip(skip).Take(2).ToList();
            return PartialView("_ProductPartial", products);
        }
        public IActionResult SearchProduct(string search)
        {
            List<Product> products = _context.Products.Where(p => p.Name.ToLower().Contains(search.ToLower())).ToList();
            return PartialView("_Search", products);
        }
    }
}

AztuLibSystem/AztuLibSystem/Areas/AdminF/Views/Product/Create.cshtml
@model Product
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
}


<div class="container ">
    <div class="row">
        <form class="forms-sample" method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="Photo"></label>
                <input asp-for="Photo" class="form-control" placeholder="name" accept="image/*">
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary mr-2">Create</button>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="_Validation" />
}

AztuLibSystem/AztuLibSystem/Areas/AdminF/Views/Product/Index.cshtml
@model IEnumerable<Product>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdminF/Views/Shared/_AdminLayout.cshtml";
    int count = 0;
}
<div class="row">
    <div class="col-lg-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Slider Table</h4>
                <a class="btn btn-success" asp-controller="Slider" asp-action="Create">Create</a>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Count</th>
                                <th>Image</th>
                                <th>Setting</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                count++;
                                <tr>
                                    <td>@count</td>
                                    <td>
                                        <img src="~/img/@item.ImageUrl" />
                                    </td>
                                    <td>
                                        <a class="btn btn-danger" asp-controller="Product" asp-action="Delete" asp-route-id="@item.Id"><i class="mdi mdi-delete"></i></a>

                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>